name: furniture_store_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4 # Pastikan minimal 2.0.4 atau lebih baru
  hive_flutter: ^1.1.0 # Pastikan minimal 1.1.0 atau lebih baru
  path_provider: ^2.1.2
  http: ^1.2.2
  flutter_local_notifications: ^17.1.2
  sensors_plus: ^3.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  lottie: ^2.7.0
  timezone: ^0.9.4
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  crypto: ^3.0.1 # Untuk hashing password
  uuid: ^4.3.3 # Untuk membuat unique session ID
  shared_preferences: ^2.2.2
  provider: ^6.0.0 # <--- TAMBAHKAN BARIS INI
  google_maps_flutter: ^2.5.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/success.json
    - assets/putrii.jpg
    - assets/nanaa.jpg
    - assets/kita.jpg